import { describe, expect, it } from "vitest";
import { loadContent } from "../../data/loadContent";
import { foundByComposition } from "../founding";
import { tracePlaythrough, validateTrace } from "../harness";
import { createRng } from "../rng";

/**
 * OB-6 — acceptance verification for the completed OB-5 milestone. Every one of the nine
 * authored origins must: be picked up by content.authoredEpoch0Places, found a leak-free run
 * whose authored Epoch-0 birth beat actually plays (the line emerges, is named, and crystallizes
 * a calling), and trace to the far future without a preset-person leak. This pins the whole
 * Epoch-0 surface so a regression in any single place's beats is caught.
 */

/**
 * Convergence Saga (SS-6): the playable roster is the immigration-WAVE places in places.json
 * (kind:"wave"). Some still carry an authored Epoch-0 from the OB milestone (ireland/bavaria/…);
 * the newer waves' Epoch-0 prose is generated by GenAI (SS-12). This acceptance test verifies:
 * every roster place founds leak-free, and every place that DOES ship an authored Epoch-0 (and is
 * still in the roster) fires its birth beat + offers all six archetypes. Dropped places
 * (south_africa, canada) still have epoch0 files on disk but are no longer foundable — they're
 * intersected out via the live roster.
 */
describe("Convergence roster: every wave founds leak-free; authored Epoch-0s are complete", () => {
  const content = loadContent();
  const rosterIds = new Set(content.places.map((p) => p.id));
  // authored-Epoch-0 places that are STILL in the playable roster.
  const authored = [...content.authoredEpoch0Places].filter((id) => rosterIds.has(id)).sort();
  // every playable starting line.
  const wavePlaces = content.places.filter((p) => p.kind !== "destination").map((p) => p.id);

  it("the roster has the expected immigration waves", () => {
    for (const wave of [
      "ireland",
      "bavaria",
      "italian",
      "ashkenazi_jewish",
      "scandinavian",
      "chinese",
      "baghdad",
    ]) {
      expect(rosterIds.has(wave), wave).toBe(true);
    }
    // dropped lines are gone.
    expect(rosterIds.has("south_africa")).toBe(false);
  });

  it("every wave place founds + traces leak-free", () => {
    for (const place of wavePlaces) {
      const def = content.places.find((p) => p.id === place);
      if (!def) continue;
      const era = def.validEras[0];
      if (!era) continue;
      const comp = {
        place,
        era,
        culture: def.defaultCulture,
        year: 1885,
        archetype: "economic" as const,
        gender: "male" as const,
        surname: "Verifier",
        seed: `wave-${place}`,
        originId: `composed:${place}:${era}`,
      };
      const founded = foundByComposition(content, comp).state;
      expect(founded.flags, place).toContain("founded_line");
      const trace = tracePlaythrough(content, comp);
      expect(
        validateTrace(trace).filter((f) => f.kind === "leak"),
        place,
      ).toEqual([]);
    }
  });

  for (const place of authored) {
    it(`${place}: founds, stamps has_authored_epoch0, and traces leak-free`, () => {
      const def = content.places.find((p) => p.id === place);
      if (!def) throw new Error(`place ${place} missing from catalog`);
      const era = def.validEras[0];
      if (!era) throw new Error(`place ${place} has no valid era`);
      const comp = {
        place,
        era,
        culture: def.defaultCulture,
        year: era === "caliphate" ? 762 : 1885,
        archetype: "economic" as const,
        gender: "male" as const,
        surname: "Verifier",
        seed: `ob6-${place}`,
        originId: `composed:${place}:${era}`,
      };
      const founded = foundByComposition(content, comp).state;
      expect(founded.flags).toContain("founded_line");
      expect(founded.flags).toContain("has_authored_epoch0");

      const trace = tracePlaythrough(content, comp);
      expect(validateTrace(trace).filter((f) => f.kind === "leak")).toEqual([]);
    });
  }

  it("the authored birth beat fires for each place (the line emerges via its own opener)", () => {
    for (const place of authored) {
      const birth = content.epoch0Events.find(
        (e) => e.place === place && e.choices.some((c) => c.setFlags?.includes("emerged")),
      );
      expect(birth, `${place} has no authored birth beat`).toBeDefined();
    }
  });

  it("every authored calling beat offers all six archetypes (no calling dead-ends)", () => {
    const SIX = [
      "athletic",
      "economic",
      "entertainment",
      "political",
      "religious",
      "technological",
    ];
    for (const place of authored) {
      const calling = content.epoch0Events.find(
        (e) => e.place === place && e.id.includes("calling_crystall"),
      );
      expect(calling, `${place} has no calling beat`).toBeDefined();
      const archs = (calling?.choices ?? [])
        .map((c) => c.setsArchetype)
        .filter(Boolean)
        .sort();
      expect(archs, `${place} calling archetypes`).toEqual(SIX);
    }
  });
});

// keep createRng import meaningful (determinism spot-check)
describe("OB-6: founding is deterministic per place", () => {
  const content = loadContent();
  it("same seed → same founded flags for a representative place", () => {
    const mk = () =>
      foundByComposition(content, {
        place: "ireland",
        era: "origins",
        culture: "irish_catholic",
        year: 1885,
        archetype: "economic" as const,
        gender: "male" as const,
        surname: "Verifier",
        seed: "ob6-determinism",
        originId: "composed:ireland:origins",
      }).state.flags;
    expect(mk()).toEqual(mk());
    expect(createRng("x").int(1, 6)).toBe(createRng("x").int(1, 6));
  });
});
