<script lang="ts">
/**
 * VD-3 — FigurePanel: the dossier's GenAI atmospheric artifact (a surveillance map, a blueprint, key-art —
 * keyed by `dossierFigureKey`, generated by the Imagen on-demand+cache pipeline like portraits). The composite
 * key maps to the asset path (`:` → `_`). If the asset isn't generated yet, the EI-9d `onerror` HIDES it so
 * the dossier degrades cleanly (the data panels carry it). NEVER a hand-drawn SVG figure.
 */
interface Props {
  /** The composite figure key (e.g. "dossier:fig:intelligence:midcentury:crime"). */
  figureKey: string;
}
const { figureKey }: Props = $props();

const src = $derived(`/assets/generated/dossiers/${figureKey.replace(/:/g, "_")}.png`);
</script>

<figure class="figure-panel">
  <img
    class="figure"
    {src}
    alt=""
    aria-hidden="true"
    decoding="async"
    onerror={(e) => {
      (e.currentTarget as HTMLImageElement).style.display = "none";
    }}
  />
</figure>

<style>
  .figure-panel {
    margin: 0;
  }
  .figure {
    display: block;
    width: 100%;
    aspect-ratio: 16 / 9;
    object-fit: cover;
    border-radius: var(--mmm-radius);
    border: 1px solid color-mix(in srgb, var(--mmm-gold-deep) 50%, transparent);
    box-shadow: var(--mmm-shadow);
  }
</style>
