<script lang="ts">
/**
 * VD-3 — FigurePanel: the dossier's GenAI artifact (a surveillance map, a blueprint, key-art — keyed by
 * `dossierFigureKey`, generated by the Imagen on-demand+cache pipeline like portraits). The composite key maps
 * to the asset path (`:` → `_`). If the asset isn't generated yet, the EI-9d `onerror` HIDES it so the dossier
 * degrades cleanly (the data panels carry it). NEVER a hand-drawn SVG figure.
 *
 * GA-DOSSIER-DIAGRAMS: the same surface also renders the INFORMATIONAL diagram variant (a tech-tree, a
 * surveillance chart) — pass a `caption` to label it as the briefing's data-figure centerpiece.
 */
interface Props {
  /** The composite figure key (e.g. "dossier:fig:intelligence:midcentury:crime" or "dossier:diagram:rnd:midcentury"). */
  figureKey: string;
  /** Optional caption — set for the GA-DOSSIER-DIAGRAMS variant so the diagram reads as a labeled figure. */
  caption?: string;
}
const { figureKey, caption }: Props = $props();

const src = $derived(`/assets/generated/dossiers/${figureKey.replace(/:/g, "_")}.png`);
</script>

<figure class="figure-panel" class:diagram={caption}>
  <img
    class="figure"
    {src}
    alt={caption ?? ""}
    aria-hidden={caption ? undefined : "true"}
    decoding="async"
    data-testid={caption ? "dossier-diagram" : "dossier-figure"}
    onerror={(e) => {
      (e.currentTarget as HTMLImageElement).style.display = "none";
    }}
  />
  {#if caption}
    <figcaption data-testid="diagram-caption">{caption}</figcaption>
  {/if}
</figure>

<style>
  .figure-panel {
    margin: 0;
  }
  .figure {
    display: block;
    width: 100%;
    aspect-ratio: 16 / 9;
    object-fit: cover;
    border-radius: var(--mmm-radius);
    border: 1px solid color-mix(in srgb, var(--mmm-gold-deep) 50%, transparent);
    box-shadow: var(--mmm-shadow);
  }
  /* GA-DOSSIER-DIAGRAMS: the diagram variant is a contained schematic (not a bled-out atmospheric plate), with
     a labeled caption beneath — it reads as the briefing's data-figure, not background. */
  .figure-panel.diagram .figure {
    aspect-ratio: 4 / 3;
    object-fit: contain;
    background: color-mix(in srgb, var(--mmm-navy-deep, #0a0f1a) 60%, transparent);
  }
  figcaption {
    margin-top: 0.4rem;
    font-family: var(--mmm-font-ui);
    font-size: 0.72rem;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    color: var(--mmm-text-dim);
  }
</style>
