/**
 * One-shot: self-host the luxury Dynasty font pairing.
 * Pulls the LATIN-subset woff2 files for the display + body faces from Google
 * Fonts into public/assets/fonts/, and writes a local @font-face stylesheet
 * (public/assets/fonts/fonts.css) referencing them — no runtime gstatic fetch,
 * so the Capacitor build works offline. Re-runnable (overwrites).
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36";
const OUT = "public/assets/fonts";

// Display = Playfair Display (dynastic luxury headers); Body = EB Garamond (refined classical).
const FAMILIES = [
  { css: "Playfair+Display:wght@500;600;700;800", slug: "playfair-display" },
  { css: "EB+Garamond:ital,wght@0,400;0,500;0,600;1,400", slug: "eb-garamond" },
];

await mkdir(OUT, { recursive: true });

/** Parse @font-face blocks, keep only the `latin` (and latin-ext) subsets. */
function parseFaces(css) {
  const faces = [];
  // Match each "/* subset */ @font-face { ... }" pair, keyed by its subset comment.
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  for (m = re.exec(css); m; m = re.exec(css)) {
    const subset = m[1];
    const body = m[2];
    if (subset !== "latin" && subset !== "latin-ext") continue;
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1] ?? "";
    const style = /font-style:\s*(\w+)/.exec(body)?.[1] ?? "normal";
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1] ?? "400";
    const url = /src:\s*url\(([^)]+)\)/.exec(body)?.[1] ?? "";
    const unicode = /unicode-range:\s*([^;]+);/.exec(body)?.[1] ?? "";
    if (url) faces.push({ subset, family, style, weight, url, unicode });
  }
  return faces;
}

let cssOut = "/* Self-hosted luxury Dynasty fonts — generated by scripts/fetch-fonts.mjs */\n";
let downloaded = 0;

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();
  const faces = parseFaces(css);
  for (const f of faces) {
    const fname = `${fam.slug}-${f.style}-${f.weight}-${f.subset}.woff2`;
    const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer());
    await writeFile(join(OUT, fname), buf);
    downloaded++;
    cssOut +=
      `@font-face {\n` +
      `  font-family: '${f.family}';\n` +
      `  font-style: ${f.style};\n` +
      `  font-weight: ${f.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/assets/fonts/${fname}') format('woff2');\n` +
      `  unicode-range: ${f.unicode};\n` +
      `}\n`;
  }
}

await writeFile(join(OUT, "fonts.css"), cssOut);
console.log(`downloaded ${downloaded} woff2 files + wrote fonts.css`);
